### ISSUE TITLE
Another Sketchfab model (static) with export issue related to mesh 

### ISSUE THREAD

**Issue by enzyme69** [kcoley/gltf2usd#54]
https://sketchfab.com/models/f74eefe9f1cd4a2795a689451e723ee9#download

Error message:
```
pxr.Tf.ErrorException: 
	Error in 'pxrInternal_v0_18__pxrReserved__::UsdGeomXformable::AddXformOp' at line 198 in file /Users/jimmygunawan/Projects/Pixar/USD/pxr/usd/lib/usdGeom/xformable.cpp : 'The xformOp 'xformOp:transform' already exists in xformOpOrder [[xformOp:transform]].'

```

**Comment by kcoley** [comment]
I'll take a look at this later tonight.  I am putting in the final touches of my refactor branch and I'll test against that.

**Comment by wave-electron** [comment]
@enzyme69  

It seems that particular sketchFab model  has many hundreds if not thousands of loose mesh artefacts inside the different rooms... not a good fit for AR QuickLook or usdz in its current form. Personally the better way to go for that kind of AR thing... shoot a 360 HD video of The Hallwyl Museum, upload to youtube and stream it to the material of sphere as a spriteKitscene in ARkit IOS app. You have some [youtube source Parser](https://github.com/jhtart/YoutubeSourceParserSwift3) available for ios on github. I know this approach works very well.. because I wrote my own Playgrounds App that did this pretty easily (couple hundred lines of code including the parser). Developers were also uploading demos of  this approach as [Arkit Portals on youtube ](https://www.youtube.com/watch?v=rIPfpGCxONQ). Great thing about this portal approach, you literally have 1000's of 360 videos available on youtube... once you know each url you can apply them as a material to a sphere. You can also create flat screens as well and stream those youtube videos to arkit.

**Comment by wave-electron** [comment]
Here's the swift playground. I use to run it on playgrounds swift on my ipad pro... playgrounds swift is buggy at the moment... but with a bit of tweaking you should be able to get this working in xcode. 

[ARKIT Portal  360 View YouTube .playground.zip](https://github.com/kcoley/gltf2usd/files/2385119/ARKIT.Portal.360.View.YouTube.playground.zip)

**Comment by kcoley** [comment]
@enzyme69 I just made an update for master which is able to convert the model to usda/usdz.  Though as @wave-electron mentioned, it is too big to load in XCode/iOS.  Though you can view it if you have usdview installed.
